ecospheres_migrator/app.py
ecospheres_migrator/templates/fragments/select_preview.html.j2
ecospheres_migrator/templates/select.html.j2

feat: style preview search list

---

ecospheres_migrator/app.py
ecospheres_migrator/batch.py
ecospheres_migrator/migrator.py
tests/conftest.py
tests/test_migrate.py

migrate: persist transform job id and add tests for batch

---

ecospheres_migrator/batch.py
ecospheres_migrator/migrator.py
tests/test_transform.py

feat: use SkippedRecord when record has working copy

---

isomorphe/app.py
isomorphe/templates/fragments/select_preview.html.j2

add links to preview table

---

isomorphe/app.py
isomorphe/batch.py
isomorphe/migrator.py
isomorphe/templates/fragments/transform_job_status.html.j2
isomorphe/transformations/default/warning.xsl
tests/test_transform.py

feat: display XSL error_log

---

isomorphe/migrator.py

fix: Only expose top-level xsl:params in UI

---

isomorphe/migrator.py

fix: Spurious geonet:info appearing in original XML

---

isomorphe/app.py
isomorphe/geonetwork.py
isomorphe/migrator.py

Could be improved even more, but at least let's not pollute the server logs?

feat: Improve log levels and use INFO by default

---

isomorphe/templates/base.html.j2
isomorphe/templates/fragments/migrate_job_status.html.j2
isomorphe/templates/fragments/migrate_update_mode.html.j2
isomorphe/templates/fragments/transform_job_status.html.j2
isomorphe/templates/header.html.j2
isomorphe/templates/login.html.j2
isomorphe/templates/migrate.html.j2
isomorphe/templates/select.html.j2
isomorphe/templates/transform.html.j2

fix #77 
Attempt at making things slightly clearer and/or slightly less scary.

feat: Improve UI wording

---

isomorphe/templates/fragments/migrate_job_status.html.j2
isomorphe/templates/fragments/transform_job_status.html.j2

fix: collapse every accordion block

---

isomorphe/app.py

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/89

fix: Disable rq job timeout

---

isomorphe/migrator.py

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/100

feat: sort transformations alphabetically

---

isomorphe/app.py
isomorphe/geonetwork.py
isomorphe/migrator.py
isomorphe/templates/fragments/migrate_update_mode.html.j2
tests/test_migrate.py

feat: update date stamp option

---

isomorphe/app.py
isomorphe/templates/fragments/migrate_job_status.html.j2
isomorphe/templates/fragments/transform_job_status.html.j2

Propagate https://github.com/ecolabdata/ecospheres-isomorphe/pull/97/files#diff-dcaab33ef3759359b2fbdf62eef525a8451015b8994592e31dc2a73f928bb023R294 to existing code.

chore: Preserve python class names passed to render_template

---

isomorphe/static/app.css
isomorphe/templates/base.html.j2
isomorphe/templates/fragments/select_transformation.html.j2

feat: more explicit display of XSLT params

---

isomorphe/static/app.css

For  https://github.com/ecolabdata/ecospheres-isomorphe/pull/new/feat/minimal-table-css

feat: minimal table css

---

doc/index.md
isomorphe/app.py
isomorphe/static/app.css
isomorphe/templates/documentation.html.j2
isomorphe/templates/select.html.j2
isomorphe/util.py
requirements.txt

Follow up fix for #71 
Fix https://github.com/ecolabdata/ecospheres/issues/313

feat: First iteration on doc

---

doc/index.md
isomorphe/app.py
isomorphe/geonetwork.py
isomorphe/migrator.py
isomorphe/static/app.css
isomorphe/templates/select.html.j2
requirements.txt
tests/conftest.py
tests/fixtures/search-response-gn3-page-1-of-3.json
tests/fixtures/search-response-gn3-page-2-of-3.json
tests/fixtures/search-response-gn3-page-3-of-3.json
tests/fixtures/search-response-gn3-page-4-of-3.json
tests/fixtures/search-response-gn4-page-1-of-3.json
tests/fixtures/search-response-gn4-page-2-of-3.json
tests/fixtures/search-response-gn4-page-3-of-3.json
tests/fixtures/search-response-gn4-page-4-of-3.json
tests/test_gn_client.py
tests/test_transform.py

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/29

Support for Geonetwork 4

---

isomorphe/geonetwork.py

fix: Record title can be a list in GN4

---

isomorphe/templates/login.html.j2

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/115

docs: Add example for portal URL

---

isomorphe/static/app.css
isomorphe/static/images/180-ring.svg
isomorphe/templates/select.html.j2

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/124.
Alternative to https://github.com/ecolabdata/ecospheres-isomorphe/pull/123 (rejected).

feat: Add spinner to preview button

---

isomorphe/app.py
isomorphe/batch.py
isomorphe/geonetwork.py
isomorphe/migrator.py
isomorphe/templates/fragments/migrate_job_status.html.j2
isomorphe/templates/fragments/migrate_results_preview.html.j2
isomorphe/templates/fragments/transform_job_status.html.j2
isomorphe/templates/fragments/transform_results_preview.html.j2
tests/test_batch.py
tests/test_gn_client.py
tests/test_migrate.py
tests/test_transform.py

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/121

feat: Preview transformation results by refined status

---

isomorphe/app.py
isomorphe/geonetwork.py
isomorphe/templates/select.html.j2

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/134

fix: Remove useless source catalog selector

---

isomorphe/geonetwork.py
isomorphe/templates/fragments/select_preview.html.j2

feat: Display record published status in preview

---

isomorphe/templates/select.html.j2

Fix https://github.com/ecolabdata/ecospheres-isomorphe/issues/143

fix: Group selection filter is not sorted
